### ISSUE TITLE
Error requesting Store. Value cannot be null (Parameter 'cookie').

### ISSUE THREAD

**Issue by josedanielr** [alexfdezsauco/YourShipping.Monitor#5]
Hola

Estoy probando este servicio pero creo que no me está funcionando correctamente, ya que no detecta los productos y en los logs veo que hace el scrapping muy rápido, teniendo en cuenta lo lento que se pone el servidor en esos horarios. El único error que se ve en los logs es el que pongo debajo, se repite cada 10 o 15 segundos aproximadamente.

Estoy usando la última imagen desde dockerhub, le estoy pasando las credenciales y también las cookies según viene en el readme.

```
2021-02-09 17:19:40.219 +00:00 [ERR] Error requesting Store from 'https://www.tuenvio.cu/villaclara/Products?depPid=0'
System.ArgumentNullException: Value cannot be null. (Parameter 'cookie')
   at System.Net.CookieContainer.Add(Uri uri, Cookie cookie)
   at YourShipping.Monitor.Server.Helpers.CookiesAwareHttpClientFactory.LoginAsync(Cookie antiScrappingCookie, String url, String username, String password) in /build/src/YourShipping.Monitor/Server/Services/CookiesAwareHttpClientFactory.cs:line 456
   at YourShipping.Monitor.Server.Helpers.CookiesAwareHttpClientFactory.GetCookiesCollectionAsync(String url) in /build/src/YourShipping.Monitor/Server/Services/CookiesAwareHttpClientFactory.cs:line 140
   at YourShipping.Monitor.Server.Helpers.CookiesAwareHttpClientFactory.<>c__DisplayClass21_0.<<GetCookiesCollectionFromCacheAsync>b__0>d.MoveNext() in /build/src/YourShipping.Monitor/Server/Services/CookiesAwareHttpClientFactory.cs:line 379
--- End of stack trace from previous location where exception was thrown ---
   at Catel.Caching.CacheStorage`2.<>c__DisplayClass32_0.<<GetFromCacheOrFetchAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Catel.Caching.CacheStorage`2.ExecuteInLockAsync[T](TKey key, Func`1 action)
   at YourShipping.Monitor.Server.Helpers.CookiesAwareHttpClientFactory.GetCookiesCollectionFromCacheAsync(String url) in /build/src/YourShipping.Monitor/Server/Services/CookiesAwareHttpClientFactory.cs:line 381
   at YourShipping.Monitor.Server.Helpers.CookiesAwareHttpClientFactory.GetCookieCollectionAsync(String url) in /build/src/YourShipping.Monitor/Server/Services/CookiesAwareHttpClientFactory.cs:line 348
   at YourShipping.Monitor.Server.Helpers.CookiesAwareHttpClientFactory.CreateHttpClientAsync(String url) in /build/src/YourShipping.Monitor/Server/Services/CookiesAwareHttpClientFactory.cs:line 118
   at YourShipping.Monitor.Server.Services.StoreScraper.GetDirectAsync(String storeUrl) in /build/src/YourShipping.Monitor/Server/Services/StoreScraper.cs:line 69
```

Cualquier idea es bienvenida. Gracias de antemano!

**Comment by alexfdezsauco** [comment]
El modo desatendido NO está funcionando desde que aparecieron las líneas en el 1er captcha. Por lo que NO debes especificar las credenciales y usar entonces el archivo cookies.txt. Si especificas las credenciales intenta autenticarse primero, de ahi el error.

**Comment by alexfdezsauco** [comment]
Por cierto mantener este archivo actualizado tambien es requerido en /data

[user-agent.txt](https://github.com/alexfdezsauco/YourShipping.Monitor/files/5966258/user-agent.txt)

Tengo que actualizar el readme.md

**Comment by josedanielr** [comment]
Listo, gracias!
